#Spring
spring.application.name=FootballManager
server.port=8080

#SQL
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#Initial values
#For simplicity let's say we have only one currency
money.currency = "USD"